#!/usr/bin/env bash
# Generate local .env files from `supabase status` and optionally merge third-party
# secrets from a hand-exported remote env file.
#
# Usage:
#   ./scripts/setup-local-env.sh
#   REMOTE_ENV=./.env.remote ./scripts/setup-local-env.sh   # paste managed secrets here
#
# Managed project: https://supabase.com/dashboard/project/eymgqjeudrmeofytnwgs
# Dashboard → Project Settings → API (URL + anon + service_role for REFERENCE only)
# Dashboard → Edge Functions → Secrets (copy values manually into .env.remote)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

REMOTE_ENV="${REMOTE_ENV:-$ROOT/.env.remote}"
ROOT_ENV="$ROOT/.env.local"
FN_ENV="$ROOT/supabase/.env.local"

if ! command -v supabase >/dev/null 2>&1 && ! command -v npx >/dev/null 2>&1; then
  echo "Install Supabase CLI or use npx." >&2
  exit 1
fi
SB() { if command -v supabase >/dev/null 2>&1; then supabase "$@"; else npx supabase "$@"; fi; }

if ! SB status >/dev/null 2>&1; then
  echo "Local Supabase is not running. Start it first:" >&2
  echo "  npx supabase start" >&2
  exit 1
fi

# shellcheck disable=SC1090
eval "$(SB status -o env 2>/dev/null | sed 's/^/export /')"

API_URL="${API_URL:-http://127.0.0.1:54321}"
ANON_KEY="${ANON_KEY:-}"
SERVICE_ROLE_KEY="${SERVICE_ROLE_KEY:-}"

if [[ -z "$ANON_KEY" || -z "$SERVICE_ROLE_KEY" ]]; then
  echo "Could not read ANON_KEY / SERVICE_ROLE_KEY from supabase status." >&2
  exit 1
fi

# ── Frontend: always points at LOCAL Supabase ─────────────────────────────────
cat > "$ROOT_ENV" <<EOF
# Auto-generated by scripts/setup-local-env.sh — local Supabase only
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY
EOF
chmod 600 "$ROOT_ENV" 2>/dev/null || true
echo "Wrote $ROOT_ENV (local API)"

# ── Edge functions: local Supabase + third-party secrets ─────────────────────
get_remote() {
  local key="$1" line=""
  for f in "$REMOTE_ENV" "$FN_ENV"; do
    [[ -f "$f" ]] || continue
    line="$(grep -E "^${key}=" "$f" 2>/dev/null | head -1 || true)"
    if [[ -n "$line" ]]; then
      echo "$line" | cut -d= -f2- | sed 's/^["'\'']//;s/["'\'']$//'
      return 0
    fi
  done
  echo ""
}

# Third-party keys to copy from managed project (Edge Function secrets)
SECRET_KEYS=(
  OPENAI_API_KEY
  ANTHROPIC_API_KEY
  MAILGUN_DOMAIN
  MAILGUN_API_KEY
  MAILGUN_FROM
  TWILIO_ACCOUNT_SID
  TWILIO_AUTH_TOKEN
  TWILIO_API_KEY_SID
  TWILIO_API_KEY_SECRET
  TWILIO_CALLER_ID
  TWILIO_TWIML_APP_SID
  TWILIO_WEBHOOK_BASE_URL
  TWILIO_A2P_BUNDLE_SID
  TWILIO_PRIMARY_CUSTOMER_PROFILE_SID
  TWILIO_TRUSTHUB_NOTIFICATION_EMAIL
  TWILIO_CUSTOMER_PROFILE_BUNDLE_SID
  TWILIO_A2P_PROFILE_BUNDLE_SID
  LEMONSQUEEZY_API_KEY
  LEMONSQUEEZY_WEBHOOK_SECRET
  LEMONSQUEEZY_STORE_ID
  LEMONSQUEEZY_VARIANT_ID
  SIKKA_APP_ID
  SIKKA_APP_SECRET
  SIKKA_WEBHOOK_SECRET
  SLACK_WEBHOOK_URL
  RESEND_API_KEY
  APP_URL
)

{
  echo "# Auto-generated by scripts/setup-local-env.sh"
  echo "# Local Supabase (do not use production URL/keys here)"
  echo "SUPABASE_URL=$API_URL"
  echo "SUPABASE_ANON_KEY=$ANON_KEY"
  echo "SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY"
  echo ""
  echo "# Local dev helpers"
  echo "TWILIO_A2P_SKIP_ENFORCEMENT=true"
  echo "TWILIO_A2P_DEV_AUTO_APPROVE=true"
  echo "# TWILIO_SKIP_WEBHOOK_SIGNATURE=true"
  echo ""
  echo "# Third-party — paste from managed project (.env.remote) or set below"
  for k in "${SECRET_KEYS[@]}"; do
    v="$(get_remote "$k")"
    if [[ -n "$v" ]]; then
      echo "$k=$v"
    else
      echo "# $k="
    fi
  done
} > "$FN_ENV"
chmod 600 "$FN_ENV" 2>/dev/null || true
echo "Wrote $FN_ENV"

if [[ -f "$REMOTE_ENV" ]]; then
  echo "Merged values from $REMOTE_ENV"
else
  echo ""
  echo "No $REMOTE_ENV found."
  echo "To copy managed Edge Function secrets:"
  echo "  1. Dashboard → Project eymgqjeudrmeofytnwgs → Edge Functions → Secrets"
  echo "  2. Copy each secret into $REMOTE_ENV as KEY=value (one per line)"
  echo "  3. Re-run: REMOTE_ENV=$REMOTE_ENV ./scripts/setup-local-env.sh"
  echo ""
  echo "Or after: npx supabase login && npx supabase link --project-ref eymgqjeudrmeofytnwgs"
  echo "  npx supabase secrets list   # names only — values are not downloadable"
fi
